name: OniaOpenCharmRun2ULenv
channels:
  - conda-forge
dependencies:
  - python = 3.9
  - xrootd = 5.3.0
  - coffea = 0.7.7
  - pip
  - root == 6.24.2
  - jupyterlab >= 3
  - ipywidgets
#  - jupyterlab-system-monitor
  - pip:
    - pyyaml
#    - python-telegram-bot
