name: OniaOpenCharmRun2ULenv
channels:
  - conda-forge
dependencies:
  - python == 3.7
  - xrootd
  - pip
  - matplotlib
  - boost-histogram >=0.10.0
  - jupyterlab >=2
  - uncertainties
  - nodejs
  - pip:
    - coffea
    - mplhep >=0.1.27
    - pyyaml
    - git+https://github.com/zfit/zfit
    