name: OniaOpenCharmRun2ULenv
channels:
  - conda-forge
dependencies:
  - python == 3.7
  - xrootd
  - pip
  - matplotlib
  - root
  - jupyterlab >=2
  - uncertainties
  - nodejs
  - zfit
  - pip:
    - coffea
    - mplhep >=0.1.27
    - pyyaml
